---
- name: Install Certbot & Route53 plugin
  apt:
    state: latest
    cache_valid_time: 3600
    pkg:
      - certbot
      - python3-certbot-dns-route53
      - python3-pexpect
  tags: certbot

- name: Install Python2 pexpect
  apt:
    state: latest
    cache_valid_time: 3600
    pkg:
      - python-pexpect
  when: ansible_distribution_major_version | int < 11
  tags: certbot

- name: Create certbot deploy-hook directory
  file:
    path: /etc/letsencrypt/renewal-hooks/deploy
    state: directory
    recurse: true
  when: certbot_deploy_hook != ""
  tags: certbot

- name: Install certbot deploy-hook if provided
  copy:
    dest: "/etc/letsencrypt/renewal-hooks/deploy/{{ certbot_deploy_hook_name }}"
    content: "{{ certbot_deploy_hook }}"
    mode: "755"
  when: certbot_deploy_hook != ""
  tags: certbot

- name: Get certificate
  expect:
    command: "certbot certonly {{ '--deploy-hook /etc/letsencrypt/renewal-hooks/deploy/' +  certbot_deploy_hook_name if certbot_deploy_hook != '' }} --dns-route53 -d {{ certbot_certificate_domains | join(' -d ') }} -m {{ certbot_email }} --agree-tos"
    responses:
      .*\(Y\)es\/\(N\)o: N
    timeout: 120
    creates: /etc/letsencrypt/live
  tags: certbot
